// (c) Copyright Microsoft Corporation.
// This source is subject to the Microsoft Permissive License.
// See http://www.microsoft.com/opensource/licenses.mspx#Ms-PL.
// All other rights reserved.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5416
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualUIAVerify {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VisualUIAVerifyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VisualUIAVerifyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VisualUIAVerify.VisualUIAVerifyResources", typeof(VisualUIAVerifyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap arrowDown {
            get {
                object obj = ResourceManager.GetObject("arrowDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrowLeft {
            get {
                object obj = ResourceManager.GetObject("arrowLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrowRight {
            get {
                object obj = ResourceManager.GetObject("arrowRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrowUp {
            get {
                object obj = ResourceManager.GetObject("arrowUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap elemTypeGeneralLive {
            get {
                object obj = ResourceManager.GetObject("elemTypeGeneralLive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap elemtyperefresh {
            get {
                object obj = ResourceManager.GetObject("elemtyperefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap elemtyperefresh2 {
            get {
                object obj = ResourceManager.GetObject("elemtyperefresh2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ExpandAll {
            get {
                object obj = ResourceManager.GetObject("ExpandAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:my=&quot;http://schemas.microsoft.com/office/infopath/2003/myXSD/2006-09-27T01:52:15&quot; xmlns:xd=&quot;http://schemas.microsoft.com/office/infopath/2003&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; xmlns:x=&quot;urn:schemas-microsoft-com:office:excel&quot; xmlns:xdExtension=&quot;http://schemas.microsoft.com/office/infopath/2003/xslt/extension&quot; xmlns:xdXDoc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FullDetailResultsXsltTemplate {
            get {
                return ResourceManager.GetString("FullDetailResultsXsltTemplate", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap gotoBack {
            get {
                object obj = ResourceManager.GetObject("gotoBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gotofirstchild {
            get {
                object obj = ResourceManager.GetObject("gotofirstchild", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gotoForward {
            get {
                object obj = ResourceManager.GetObject("gotoForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gotolastchild {
            get {
                object obj = ResourceManager.GetObject("gotolastchild", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gotonextsibling {
            get {
                object obj = ResourceManager.GetObject("gotonextsibling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gotoparent {
            get {
                object obj = ResourceManager.GetObject("gotoparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gotoprevsibling {
            get {
                object obj = ResourceManager.GetObject("gotoprevsibling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ieIcon {
            get {
                object obj = ResourceManager.GetObject("ieIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap orderAlphabetical {
            get {
                object obj = ResourceManager.GetObject("orderAlphabetical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap orderCategorized {
            get {
                object obj = ResourceManager.GetObject("orderCategorized", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:my=&quot;http://schemas.microsoft.com/office/infopath/2003/myXSD/2006-09-27T01:52:15&quot; xmlns:xd=&quot;http://schemas.microsoft.com/office/infopath/2003&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; xmlns:x=&quot;urn:schemas-microsoft-com:office:excel&quot; xmlns:xdExtension=&quot;http://schemas.microsoft.com/office/infopath/2003/xslt/extension&quot; xmlns:xdXDoc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OverallResultsXsltTemplate {
            get {
                return ResourceManager.GetString("OverallResultsXsltTemplate", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap quickFind {
            get {
                object obj = ResourceManager.GetObject("quickFind", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:my=&quot;http://schemas.microsoft.com/office/infopath/2003/myXSD/2006-10-11T21:18:04&quot; xmlns:xd=&quot;http://schemas.microsoft.com/office/infopath/2003&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; xmlns:x=&quot;urn:schemas-microsoft-com:office:excel&quot; xmlns:xdExtension=&quot;http://schemas.microsoft.com/office/infopath/2003/xslt/extension&quot; xmlns:xdXDoc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestLogXsltTemplate {
            get {
                return ResourceManager.GetString("TestLogXsltTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:my=&quot;http://schemas.microsoft.com/office/infopath/2003/myXSD/2006-09-28T19:28:22&quot; xmlns:xd=&quot;http://schemas.microsoft.com/office/infopath/2003&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; xmlns:x=&quot;urn:schemas-microsoft-com:office:excel&quot; xmlns:xdExtension=&quot;http://schemas.microsoft.com/offi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResultsXsltTemplate {
            get {
                return ResourceManager.GetString("TestResultsXsltTemplate", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap testToRun {
            get {
                object obj = ResourceManager.GetObject("testToRun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap testToRun1 {
            get {
                object obj = ResourceManager.GetObject("testToRun1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap testToRunWithChildren {
            get {
                object obj = ResourceManager.GetObject("testToRunWithChildren", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
